[project]
name = "heirloom"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token"

[[project.requirements]]
contract_id = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.usdcx"

[contracts.heirloom-vault-v10]
path = "contracts/heirloom-vault.clar"
clarity_version = 4
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
