[project]
name = "heirloom"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "ST126WM9ZYGYSNFM2YDV11MS0XMCJ91Q20HPNZY4T.test-sbtc-faucet"

[[project.requirements]]
contract_id = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.usdcx"

[contracts.heirloom-vault-v7]
path = "contracts/heirloom-vault.clar"
clarity_version = 4
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
